pin "application"
pin "@hotwired/turbo-rails"
pin "@hotwired/stimulus"
pin "@hotwired/stimulus-loading"
pin_all_from "app/javascript/controllers", under: "controllers"
pin "jquery", to: "https://code.jquery.com/jquery-3.6.0.min.js"
pin "autosuggestion", to: "autosuggestion.js"
pin "autocomplete", to: "autocomplete.js"
pin_all_from "app/javascript/channels", under: "channels"
pin "message_form_controller", to: "controllers/message_form_controller.js"
pin "conversation_channel", to: "channels/conversation_channel.js"
